### ISSUE TITLE
Does not build today - method issue

### ISSUE THREAD

**Issue by quicklisp** [Shinmera/cl-all#1]
Unhandled SB-PCL::FIND-METHOD-LENGTH-MISMATCH in thread #<SB-THREAD:THREAD "main thread" RUNNING {10005D85B3}>: The generic function #<STANDARD-GENERIC-FUNCTION CL-ALL:EVAL-IN-LISP (10)> takes 3 required arguments; was asked to find a method with specializers (CLASP PATHNAME)
    See also:
      The ANSI Standard, Function FIND-METHOD

Full log is here: http://report.quicklisp.org/2019-03-06/failure-report/cl-all.html#cl-all

**Comment by Shinmera** [comment]
I can't reproduce this, nor find a two-arg method definition in the source.

**Comment by quicklisp** [comment]
Thanks for checking, it looks like there was some local caching on my end that was fouling things up.
